macro(TARGET_GLM)
    target_compile_definitions(${TARGET_NAME} PRIVATE GLM_FORCE_RADIANS)
    target_compile_definitions(${TARGET_NAME} PRIVATE KHRPP_USE_GLM)
    target_include_directories(${TARGET_NAME} PRIVATE ${CMAKE_SOURCE_DIR}/external/glm)
endmacro()
