name: CMake CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: mkdir
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: cmake configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE
    - name: build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Release 
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C Debug
